# Generated by Django 5.2.8 on 2025-11-28 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_colpleted_task_comleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='comleted',
            new_name='completed',
        ),
    ]
